# Generated by Django 5.1.1 on 2024-09-08 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_twitterpost'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitterpost',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='twitterpost',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='twitterpost',
            name='content',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='twitterpost',
            name='likes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
