# Generated by Django 5.1.1 on 2024-09-08 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_twitterpost_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='twitterpost',
            old_name='created_at',
            new_name='date_created',
        ),
    ]
