# Generated by Django 5.1.1 on 2024-09-09 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_created_at_twitterpost_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitterpost',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.userprofile'),
        ),
    ]
