# Generated by Django 5.1.1 on 2024-09-10 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_userprofile_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_image',
        ),
    ]
