# Generated by Django 5.1.1 on 2024-09-10 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_userprofile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitterpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
