# Generated by Django 5.1.1 on 2024-09-18 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio',
            name='content',
            field=models.TextField(max_length=250),
        ),
    ]
