# Generated by Django 5.1.1 on 2024-09-18 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_bio_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio',
            name='content',
            field=models.CharField(max_length=225),
        ),
    ]
